# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mMVNsTFKvbSH-V9u52ZV2fT3-tTFxR84
"""

import pandas as pd
import numpy as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('titanic')

df.head()

df.shape

df=df.loc[:,['survived','pclass','age','sibsp','parch']]
df.head()

df.isnull().sum()

fill_null=df.fillna(age_mean)
fill_null

#df=df.loc[:,['survived','pclass','age','sibsp','parch']]

df.isnull().sum()

mean_age=df["age"].mean()
mean_age

df=df.fillna({'age':mean_age})

df.isnull().sum()

x=df.iloc[:,1:5]

x.head()

y=df.iloc[:,0]
y.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

y_train

x_train

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()
clf.fit(x_train, y_train)

pred=clf.predict(x_test)

pred

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)